<div class="loginWrapper">
    <div class="loginLogo"><img src="images/loginLogo.png" alt="" /></div>
    <div class="widget">
        <div class="title"><img src="images/icons/dark/files.png" alt="" class="titleIcon" /><h6><?php echo $this->title; ?></h6></div>
			<?php if(count($this->messages) > 0): ?>
			        <?php foreach($this->messages as $message): ?>
			            <p><?php echo $message; ?></p>
			        <?php endforeach; ?>
			<?php endif; ?>
         <?php if(isset($this->error)){
          echo '<p>'.$this->error.'</p>';
        }
        ?>
       <?php echo $this->form ?>
    </div>
</div>    