

<div class="ajaxWrapper">
    <div class="widget">
        <div class="title titleAutoHeight">
            <h6><i18n><?php echo $this->title; ?></i18n></h6>
        </div>
        <div class="body">
            <?php if(count($this->messages) > 0): ?>
            <?php foreach($this->messages as $message): ?>
                <p><?php echo $message; ?></p>
                <?php endforeach; ?>
            <?php endif; ?>

            <?php echo $this->success?$this->success:""; ?>
            <?php echo $this->error?$this->error:""; ?>
            <?php echo $this->form; ?>
            <div class="ajaxResponse"></div>
            <script type="text/javascript">
                $(document).ready(function() {
                    $(function() {
                        $( "#date_start_availability" ).datepicker({ dateFormat: 'yy-mm-dd' });
                        $( "#date_finish_availability" ).datepicker({ dateFormat: 'yy-mm-dd' });
                    });

                });
            </script>
        </div>
    </div>
</div>
