<h2><?php echo $this->title; ?></h2>
<p><a class="przycisk" href="<?php echo $this->url(array('controller'=>'additionalfield',
          'action'=>'list'));?>">powrót do listy</a></p>
<?php echo $this->success; ?>
<?php echo $this->error; ?>
<?php echo $this->form; ?>

<!--<div id="additional"></div>
<input type="submit" name="add" id="add" value="Dodaj" />
			
<script type="text/javascript">
  var i=0;
  $(document).ready(function()
  {
  	  $('input#add').click(function()
  	  {
  	       $('div#additional').append('<div id="person'+i+'">'+
               '<input type="text" name="type'+i+'" tabindex="8">'+
               '<input type="text" name="label'+i+'" value="" tabindex="9">'+
               '</div>');
                
                i++;
		  
	  });
  });
</script>-->