<div class="widget">
<div class="title titleAutoHeight">
	<img class="titleIcon" src="<?php echo $this->baseUrl(); ?>/images/icons/control/32/settings2.png" alt="" />
	<h6><i18n><?php echo $this->title; ?></i18n></h6>
</div>
</div>
<div class="ajaxWrapper">
<div class="widget">
	<div class="title">
		<h6>Edycja ustawień</h6>
	</div>
	<div class="body">
<!-- BEGIN WIDGET BODY -->

<?php echo $this->success; ?>
<?php echo $this->error; ?>
<?php echo $this->form; ?>

	  
<div class="ajaxResponse"></div>

<!-- END WIDGET BODY -->
	</div>
</div>
</div>

