<?php echo $this->doctype('XHTML1_TRANSITIONAL') ?>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
    <?php
    // charset ustawiany jest w bootstrapie
     echo $this->headMeta()->setName('viewport', 'width=device-width; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;' ); ?>
    <?php echo $this->headTitle(); ?>
    <base href="<?php echo $this->layout()->link.'/'; ?>" />

    <link href="<?php echo $this->layout()->link; ?>/css/main.css" rel="stylesheet" type="text/css" />
	 <?php echo $this->jQuery()->setCdnSsl(true)->setVersion('1.7')->enable()->setUiLocalPath('https://ajax.googleapis.com/ajax/libs/jqueryui/1.8/jquery-ui.min.js')->UIenable(); ?>
	<?php echo $this->headScript()
	
									->appendFile($this->layout()->link.'/js/plugins/charts/jquery.flot.pie.js')
									->appendFile($this->layout()->link.'/js/plugins/charts/jquery.flot.orderBars.js')
									->appendFile($this->layout()->link.'/js/plugins/charts/jquery.flot.js')
                                      ; ?>


	<script type = "text/javascript">
	$(document).ready(function() {
		 $("img[src='']").remove();

	});
	</script>

</head>

<body class="nobg loginPage">


<?php echo $this->layout()->content; ?>


<div class="clear"></div>
</body>
</html>