
<div class="widgets">
<div class="ajaxWrapper">
<div class="widget">
    <div class="title titleAutoHeight">
    		<h6><?php echo $this->title; ?></h6>
    </div>
	<div class="body">
			<?php if(count($this->messages) > 0): ?>
			        <?php foreach($this->messages as $message): ?>
			            <p><?php echo $message; ?></p>
			        <?php endforeach; ?>
			<?php endif; ?>
			
<?php echo $this->success?$this->success:""; ?>
<?php echo $this->error?$this->error:""; ?>
<?php echo $this->form; ?>
	
<div class="ajaxResponse"></div>


	</div>
</div>
</div>
</div>