

<div class="ajaxWrapper">
<div class="widget">
	<div class="title">
		<h6><i18n>title.change.password</i18n></h6>
	</div>
	<div class="body">
				<?php if(count($this->messages) > 0): ?>
			        <?php foreach($this->messages as $message): ?>
			            <p><?php echo $message; ?></p>
			        <?php endforeach; ?>
			<?php endif; ?>
<!-- BEGIN WIDGET BODY -->

<?php echo $this->success; ?>
<?php echo $this->error; ?>
<?php echo $this->form; ?>


	  

<!-- END WIDGET BODY -->
	</div>
</div>
</div>

